//Best Sellers
// let bestSellers = [
//     {
//       img:"BestSellers/best6.png" ,
//       description: "FIRST WRINKLES / THE “RIDES” KILLER",
//       price: 885
//     },
//     {
//       img:"BestSellers/best4.jpg",
//       description: "Cream Emulsion Hyaluronic Acid 1% + Betaine 1% ",
//       price: 1100
//     },
//     {
//       img:"BestSellers/best5.jpg" ,
//       description: "Cream Suspension Azelaic Acid 11.1%",
//       price: 1000
//     },
//     {
//       img:"BestSellers/best1.jpg" ,
//       description: "Dr. Jart Cicapair Cream",
//       price: 500
//     },
//     {
//       img:"BestSellers/best2.jpg" ,
//       description: "Dr.Jart+ Cicapair Sleepair Ampoule-In Mask",
//       price: 299
//     },
//     {
//       img:"BestSellers/best3.jpg" ,
//       description: "PURITO From Green Cleansing Oil",
//       price: 780
//     },
//     {
//       img:"BestSellers/best7.jpg" ,
//       description: "Magnesium mist / Soothing spray for sensitive skin",
//       price: 299
//     },
//     {
//       img:"BestSellers/best8.jpg" ,
//       description: "Radiance Lifting Eye Contour",
//       price: 780
//     },
//   ]



//Novexpert
//Category: Cream, Serum, Mask, Eye Care, Mist, Scrub, Purifying Fluid, Cleanser,  Oil,  Fluid, Lotion
//Range: Omega, Hyaluronic Acid, Vitamin-C, Zinc, Magnesium, Pro-collagen, Pro-melanin
let novexpertProducts = [
    {
        id: 1,
        category:"Cream",
        range: "Omega",
        img: "Novexpert/1.png",
        name: "Rich Protective Cream",
        description: "",
        price: 39,
        size: "40ml",

    },
    {
        id: 2,
        category:"Serum",
        range: "Hyaluronic Acid",
        img: "Novexpert/2.png",
        name: "Booster Serum with Hyaluronic Acid",
        description: "",
        price: 49,
        size: "30ml",
    },
    {
        id: 3,
        category:"Cream",
        img: "Novexpert/3.png",
        range: "Omega",
        name: "Extra Rich Repair Cream",
        description: "",
        price: 39,
        size: "40ml",
    },
    {
        id: 4,
        category:"Serum",
        range: "Vitamin-C",
        img: "Novexpert/4.png",
        name: "Booster with Vitamin C",
        description: "",
        price: 49,
        size: "30ml",
    },
    {
        id: 5,
        category:"Mask",
        range: "Omega",
        img: "Novexpert/5.png",
        name: "SOS Ultra-Nourishing Mask",
        description: "",
        price: 29,
        size: "50ml",
    },
    {
        id: 6,
        category:"Cleanser",
        range: "Vitamin-C",
        img: "Novexpert/6.png",
        name: "Express Radiant Cleansing Foam",
        description: "",
        price: 18,
        size: "150ml",
    },
    {
        id: 7,
        category:"Cleanser",
        range: "Zinc",
        img: "Novexpert/7.png",
        name: "Clear Skin Foaming Gel",
        description: "",
        price: 17,
        size: "150gr",
    },
    {
        id: 8,
        category:"Cream",
        range: "Hyaluronic Acid",
        img: "Novexpert/8.png",
        name: "The Repulp Cream",
        description: "",
        price: 39,
        size: "40ml",
    },
    {
        id: 9,
        category:"Cream",
        range: "Zinc",
        img: "Novexpert/9.png",
        name: "Express Blemish Care",
        description: "",
        price: 14,
        size: "7gr",
    },
    {
        id: 10,
        category:"Eye Care",
        range: "Vitamin-C",
        img: "Novexpert/10.png",
        name: "Radiance Lifting Eye Contour",
        description: "",
        price: 36,
        size: "15ml",
    },
    {
        id: 11,
        category:"Cream",
        range: "Magnesium",
        img: "Novexpert/11.png",
        name: "Velvety Hydro-Biotic Cream",
        description: "",
        price: 21,
        size: "30ml",
    },
    {
        id: 12,
        category:"Eye Care",
        range: "Pro-collagen",
        img: "Novexpert/12.png",
        name: "Expert Anti-Aging Eye Contour",
        description: "",
        price: 36,
        size: "15ml",
    },
    {
        id: 13,
        category:"Mist",
        range: "Zinc",
        img: "Novexpert/13.png",
        name: "Trio-Zinc Mist",
        description: "",
        price: 18,
        size: "150ml",
    },
    {
        id: 14,
        category:"Purifying Fluid",
        range: "Zinc",
        img: "Novexpert/14.png",
        name: "Purifying fluid",
        description: "",
        price: 25,
        size: "30ml",
    },
    {
        id: 15,
        category:"Scrub",
        range: "Magnesium",
        img: "Novexpert/15.png",
        name: "Velvety Scrub Hydro-Biotic",
        description: "",
        price: 14,
        size: "60ml",
    },
    {
        id: 16,
        category:"Cleanser",
        range: "Omega",
        img: "Novexpert/16.png",
        name: "Cleansing Oil with 5 Omegas",
        description: "",
        price: 25,
        size: "150ml",
    },
    {
        id: 17,
        category:"Cleanser",
        range: "Zinc",
        img: "Novexpert/17.png",
        name: "Purifying gel",
        description: "",
        price: 25,
        size: "30ml",
    },
    {
        id: 18,
        category:"Cream",
        range: "Pro-melanin",
        img: "Novexpert/18.png",
        name: "The Caramel Cream Ivory Radiance",
        description: "",
        price: 25,
        size: "30ml",
    },
    {
        id: 19,
        category:"Oil",
        range: "Omega",
        img: "Novexpert/19.png",
        name: "5 Omega Booster Oil",
        description: "",
        price: 49,
        size: "30ml",
    },
    {
        id: 20,
        category:" Mask",
        range: "Vitamin-C",
        img: "Novexpert/20.png",
        name: "The Expert Exfoliator",
        description: "",
        price: 25,
        size: "50ml",
    },
    {
        id: 21,
        category:"Cream",
        range: "Vitamin-C",
        img: "Novexpert/21.png",
        name: "The Night Peeling Cream",
        description: "",
        price: 39,
        size: "40ml",
    },
    {
        id: 22,
        category:"Fluid",
        range: "Pro-collagen",
        img: "Novexpert/22.png",
        name: "The Expert Anti-Aging Fluid",
        description: "",
        price: 39,
        size: "40ml",
    },
    {
        id: 23,
        category:"Cream",
        range: "Pro-collagen",
        img: "Novexpert/23.png",
        name: "The Expert Anti-Aging Cream",
        description: "",
        price: 39,
        size: "40ml",
    },
    {
        id: 24,
        category:"Exfoliator, Mask, Scrub",
        range: "Magnesium",
        img: "Novexpert/24.png",
        name: "Velvety Hydro-Biotic Fluid",
        description: "",
        price: 22,
        size: "30ml",
    },
    {
        id: 25,
        category:"Lotion",
        range: "Zinc",
        img: "Novexpert/25.png",
        name: "Peeling Night Lotion",
        description: "",
        price: 25,
        size: "115ml",
    },
    {
        id: 26,
        category:"Mist",
        range: "Magnesium",
        img: "Novexpert/26.png",
        name: "Magnesium Mist",
        description: "",
        price: 7,
        size: "150ml",
    },
    {
        id: 27,
        category:"Mask",
        range: "Magnesium",
        img: "Novexpert/27.png",
        name: "Detox Mask with Creamy Pink Clay",
        description: "",
        price: 15,
        size: "75ml",
    },
    {
        id: 28,
        category:"Mist",
        range: "Magnesium",
        img: "Novexpert/28.png",
        name: "Milky Cleanser Hydro-Biotic",
        description: "",
        price: 19,
        size: "200ml",
    },


]

//Pulpe de Vie
//Category: Eye Care, Face Care, Body & Hair, Face masks and scrubs, 
//Range: Radiance and Energy, Detox, First Wrinkels, Anti-oxidant, Hygiene, [Im]perfection, Anti-ageing, Hair mask & Conditioner, Hydratation, Sensible Skins 
let pulpeDeVieProducts = [
    {
        id: 1,
        category:"Eye Care",
        range: "Radiance and Energy",
        img: "PulpeDeVie/1.jpg",
        name: "Anti-fatigue glow eye care",
        description: "",
        price: 10,
        size: "15ml",

    },
    {
        id: 2,
        category:"Face Care",
        range: "[Im]perfection",
        img: "PulpeDeVie/2.jpg",
        name: "Moisturising blur face care",
        description: "",
        price: 11,
        size: "40ml",
    },
    {
        id: 3,
        category:"Body & Hair",
        range: "Hygiene",
        img: "PulpeDeVie/3.jpg",
        name: "Balancing Shampoo",
        description: "",
        price: 6,
        size: "150ml",

    },
    {
        id: 4,
        category:"Body & Hair",
        range: "Hygiene",
        img: "PulpeDeVie/4.jpg",
        name: "Gentle Shampoo",
        description: "",
        price: 8,
        size: "150ml",
    },
    {
        id: 5,
        category:"Face Care",
        range: "First Wrinkels",
        img: "PulpeDeVie/5.jpg",
        name: "Eye care and Mask",
        description: "",
        price: 13,
        size: "15ml",

    },
    {
        id: 6,
        category:"Face Care",
        range: "Radiance and Energy",
        img: "PulpeDeVie/6.jpg",
        name: "Illuminating & moisturising face care",
        description: "",
        price: 12,
        size: "30ml",
    },
    {
        id: 7,
        category:"Face Care",
        range: "[Im]perfection",
        img: "PulpeDeVie/7.jpg",
        name: "Facial Perfecting Serum",
        description: "",
        price: 12,
        size: "30ml",
    },
    {
        id: 8,
        category:"Face Care",
        range: "Radiance and Energy",
        img: "PulpeDeVie/8.jpg",
        name: "Self-Tanning cream",
        description: "",
        price: 10,
        size: "40ml",
    },
    {
        id: 9,
        category:"Face Care",
        range: "[Im]perfection",
        img: "PulpeDeVie/9.jpg",
        name: "Micellar jelly make-up remover",
        description: "",
        price: 8,
        size: "200ml",
    },
    {
        id: 10,
        category:"Face Care",
        range: "[Im]perfection",
        img: "PulpeDeVie/10.jpg",
        name: "Cleaning foam",
        description: "",
        price: 8,
        size: "125ml",
    },
    {
        id: 11,
        category:"Face Care",
        range: "Detox",
        img: "PulpeDeVie/11.jpg",
        name: "Micellar water make-up remover",
        description: "",
        price: 9,
        size: "400ml",
    },
    {
        id: 12,
        category:"Face Care",
        range: "First Wrinkels",
        img: "PulpeDeVie/12.jpg",
        name: "First wrinkles cream",
        description: "",
        price: 12,
        size: "30ml",
    },
    {
        id: 13,
        category:"Face masks and scrubs",
        range: "Anti-ageing",
        img: "PulpeDeVie/13.jpg",
        name: "Anti-Ageing mask",
        description: "",
        price: 4,
        size: "1 application",
    },
    {
        id: 14,
        category:"Body & Hair",
        range: "Hygiene",
        img: "PulpeDeVie/14.jpg",
        name: "Energizing shower gel",
        description: "",
        price: 3,
        size: "200ml",
    },
    {
        id: 15,
        category:"Body & Hair",
        range: "Hair mask & Conditioner",
        img: "PulpeDeVie/15.jpg",
        name: "Untangling Hair Mask",
        description: "",
        price: 6,
        size: "150ml",
    },
    {
        id: 16,
        category:"Face Care",
        range: "Hydratation",
        img: "PulpeDeVie/16.jpg",
        name: "The cleanser",
        description: "",
        price: 8,
        size: "50ml",
    },
    {
        id: 17,
        category:"Face Care",
        range: "Hydratation",
        img: "PulpeDeVie/17.jpg",
        name: "3-care routine MOISTURIZING",
        description: "",
        price: 29,
        size: "400ml",
    },
    {
        id: 18,
        category:"Face Care",
        range: "Hydratation",
        img: "PulpeDeVie/18.jpg",
        name: "Face Moisturizer Cream HYDRATATION",
        description: "",
        price: 11,
        size: "40ml",
    },
    {
        id: 19,
        category:"Face Care",
        range: "Radiance and Energy",
        img: "PulpeDeVie/19.jpg",
        name: "Cleaning foam",
        description: "",
        price: 8,
        size: "125ml",
    },
    {
        id: 20,
        category:"Body & Hair",
        range: "Hygiene",
        img: "PulpeDeVie/20.jpg",
        name: "Nourishing shower gel",
        description: "",
        price: 4,
        size: "200ml",
    },
    {
        id: 21,
        category:"Face Care",
        range: "Radiance and Energy",
        img: "PulpeDeVie/21.jpg",
        name: "Face mask & scrub",
        description: "",
        price: 10,
        size: "400ml",
    },
    {
        id: 22,
        category:"Face Care",
        range: "Hydratation",
        img: "PulpeDeVie/22.jpg",
        name: "Hydrating face serum",
        description: "",
        price: 14,
        size: "30ml",
    },
    {
        id: 23,
        category:"Face Care",
        range: "Sensible Skins ",
        img: "PulpeDeVie/23.jpg",
        name: "Micellar water make-up remover",
        description: "",
        price: 8,
        size: "400ml",
    },
    {
        id: 24,
        category:"Face Care",
        range: "Sensible Skins ",
        img: "PulpeDeVie/24.jpg",
        name: "Moisturising facial gel",
        description: "",
        price: 10,
        size: "40ml",
    }
    




]

//True Alchemy
//Category: Cream, Mask, Cleanser, Serum, Eye Care, Sets
//Range:   Niacinamide, Cantella Asiatica, Panthenol
let truAlchemyProducts = [
    {
        id: 1,
        category:"Cream",
        range: "Hyaluronic Acid",
        img: "TruAlchemy/1.jpg",
        name: "QUENCH CRÈME, Daily Moisturizer with Hyaluronic",
        description: "",
        price: 39,
        size: "15ml",

    },
    {
        id: 2,
        category:"Mask",
        range: "Hyaluronic Acid, Vitamin-C, Niacinamide",
        img: "TruAlchemy/2.jpg",
        name: "MYSTIC MASK, Enzyme Treatment with Activated Vitamin C, Niacinamide + Hyaluronic",
        description: "",
        price: 56,
        size: "40ml",
    },
    {
        id: 3,
        category:"Serum",
        range: "Vitamin-C",
        img: "TruAlchemy/3.jpg",
        name: "GLOW SERUM, Activated Vitamin C",
        description: "",
        price: 39,
        size: "20ml",

    },
    {
        id: 4,
        category:"Eye Care",
        range: "Hyaluronic Acid",
        img: "TruAlchemy/4.jpg",
        name: "EYE ELIXIR, Cooling Eye Treatment with Hyaluronic",
        description: "",
        price: 56,
        size: "40ml",
    },
    {
        id: 5,
        category:"Serum",
        range: " Niacinamide",
        img: "TruAlchemy/5.jpg",
        name: "Brightening Serum + Spot Corrector with Niacinamide",
        description: "",
        price: 39,
        size: "15ml",

    },
    {
        id: 6,
        category:"Sets",
        range: " Vitamin-C, Niacinamide",
        img: "TruAlchemy/6.jpg",
        name: "A daily trio for smooth, glowing skin: Celestial Cleanser + Glow Serum + Quench Crème",
        description: "",
        price: 97,
        size: "150ml",
    },
    {
        id: 7,
        category:"Sets",
        range: "Hyaluronic Acid",
        img: "TruAlchemy/7.jpg",
        name: "Spot Check + Eye Elixir for bright, dewy, illuminated skin that lasts throughout the day",
        description: "",
        price: 89,
        size: "100ml",

    },
    {
        id: 8,
        category:"Serum",
        range: "Collagen",
        img: "TruAlchemy/8.jpg",
        name: "NURTURING LASH SERUM WITH COLLAGEN PEPTIDES",
        description: "",
        price: 41,
        size: "10ml",
    },
    

]

//Purito
//Category: Cream, Mask, Cleanser, Serum, Eye Care, Sets,Toner
//Range:  Vitamin-C,  Niacinamide, Panthenol, Sea Buckthorn, Olive oil, Cantella Asiatica
let puritoProducts=[
    {
        id: 1,
        category:"Toner",
        range: "Panthenol",
        img: "Purito/1.jpg",
        name: "Centella Green Level Calming Toner",
        description: "",
        price: 22,
        size: "200ml",

    },
    {
        id: 2,
        category:"Eye Care",
        range: "Panthenol",
        img: "Purito/2.jpg",
        name: "Centella Green Level Eye Cream",
        description: "",
        price: 14,
        size: "30ml",
    },
    {
        id: 3,
        category:"Cream",
        range: "Niacinamide",
        img: "Purito/3.jpg",
        name: "QUENCH CRÈME, Daily Moisturizer with Hyaluronic",
        description: "",
        price: 19,
        size: "50ml",

    },
    {
        id: 4,
        category:"Serum",
        range: "Niacinamide",
        img: "Purito/4.jpg",
        name: "Centella Green Buffet Serum",
        description: "",
        price: 19,
        size: "60ml",
    },
    {
        id: 5,
        category:"Eye Care",
        range: "Cantella Asiatica",
        img: "Purito/5.jpg",
        name: "Centella Unscented Eye Cream 30ml",
        description: "",
        price: 14,
        size: "30ml",

    },
    {
        id: 6,
        category:"Sets",
        range: "Cantella Asiatica",
        img: "Purito/6.png",
        name: "Centella Unscented line travel kit (mini)",
        description: "",
        price: 19,
        size: "Toner(30ml), Serum(15ml), Cream(12ml)",
    },
    {
        id: 7,
        category:"Cream",
        range: "Cantella Asiatica",
        img: "Purito/7.jpg",
        name: "Centella Unscented Recovery Cream",
        description: "",
        price: 20,
        size: "50ml",

    },
    {
        id: 8,
        category:"Serum",
        range: "Cantella Asiatica",
        img: "Purito/8.jpg",
        name: "Centella Unscented Serum",
        description: "",
        price: 21,
        size: "60ml",
    },
    {
        id:9,
        category:"Toner",
        range: "Cantella Asiatica",
        img: "Purito/9.jpg",
        name: "Centella Unscented Toner",
        description: "",
        price: 22,
        size: "200ml",

    },
    {
        id: 10,
        category:"Cream",
        range: "Niacinamide",
        img: "Purito/10.jpg",
        name: "Deep Sea Pure Water Cream",
        description: "",
        price: 19,
        size: "50gr",
    },
    {
        id: 11,
        category:"Cream",
        range: "Niacinamide, Sea Buckthorn",
        img: "Purito/11.jpg",
        name: "Sea Buckthorn Vital 70 Cream",
        description: "",
        price:199,
        size: "50ml",

    },
    {
        id: 12,
        category:"Cream",
        range: "Cantella Asiatica",
        img: "Purito/12.jpg",
        name: "Dermide Cica Barrier Sleeping Pack",
        description: "",
        price: 19,
        size: "80ml",
    },
    {
        id: 13,
        category:"Cleanser",
        range: "Olive oil",
        img: "Purito/13.jpg",
        name: "Green Cleansing Oil",
        description: "",
        price: 21,
        size: "200ml",
    },

    {
        id: 14,
        category:"Cleanser",
        range: "Cantella Asiatica",
        img: "Purito/14.jpg",
        name: "Defence Barrier Ph Cleanser",
        description: "",
        price: 21,
        size: "150ml",
    },

    {
        id: 15,
        category:"Toner",
        range: "Cantella Asiatica",
        img: "Purito/15.jpg",
        name: "DermaHA-3 Liquid",
        description: "",
        price: 22,
        size: "200ml",
    },

    {
        id: 16,
        category:"Serum",
        range: "Vitamin-C",
        img: "Purito/16.png",
        name: "Pure Vitamin C Serum 60ml",
        description: "",
        price: 20,
        size: "60ml",
    },



]

//Dr.Jart
//Category: Colour Correcting, Cream, Mask, Serum, Sets, Toner, Eye Care, Mist, 
//Range: BB Cream, Ceramide complex, Hyaluronic Acid, Cantella Asiatica, Niacinamide, 
let drJartProducts=[
    {
        id: 1,
        category:"Colour Correcting",
        range: "BB Cream",
        img: "DrJart/1.jpg",
        name: "CICAPAIR™ TIGER GRASS COLOUR CORRECTING TREATMENT",
        description: "",
        price: 80,
        size: "50ml",

    },
    {
        id: 2,
        category:"Cream",
        range: "Ceramide complex",
        img: "DrJart/2.jpg",
        name: "CERAMIDIN™ CREAM",
        description: "",
        price: 70,
        size: "50ml",

    },
    {
        id: 3,
        category:"Cream",
        range: "Hyaluronic Acid",
        img: "DrJart/3.jpg",
        name: "VITAL HYDRA SOLUTION™ BIOME WATER CREAM",
        description: "",
        price: 60,
        size: "100ml",

    },
    {
        id: 4,
        category:"Cream",
        range: "Cantella Asiatica",
        img: "DrJart/4.jpg",
        name: "CICAPAIR™ TIGER GRASS RE.PAIR CREAM",
        description: "",
        price: 72,
        size: "100ml",

    },
    {
        id: 5,
        category:"Cream",
        range: "Niacinamide",
        img: "DrJart/5.jpg",
        name: "CTRL-A TEATREEMENT™ MOISTURISER",
        description: "",
        price: 45,
        size: "100ml",

    },
    {
        id: 6,
        category:"Serum",
        range: "Ceramide complex",
        img: "DrJart/6.jpg",
        name: "CERAMIDIN™ SERUM",
        description: "",
        price: 85,
        size: "100ml",

    },
    {
        id: 7,
        category:"Sets",
        range: "Ceramide complex",
        img: "DrJart/7.jpg",
        name: "CERAMIDIN™ TRAVEL KIT",
        description: "",
        price: 48,
        size: "100ml",

    },
    {
        id: 8,
        category:"Cream",
        range: "Cantella Asiatica",
        img: "DrJart/8.jpg",
        name: "CICAPAIR™ TIGER GRASS CALMING GEL CREAM",
        description: "",
        price: 56,
        size: "100ml",

    },
    {
        id: 9,
        category:"Sets",
        range: "Cantella Asiatica",
        img: "DrJart/9.jpg",
        name: "CICAPAIR™ YOUR FIRST TRIAL KIT",
        description: "",
        price: 67,
        size: "100ml",

    },
    {
        id: 10,
        category:"Sets",
        range: "Hyaluronic Acid",
        img: "DrJart/10.jpg",
        name: "MICROBIOME HYDRATING DUO",
        description: "",
        price: 35,
        size: "100ml",

    },
    {
        id: 11,
        category:"Cream",
        range: "Ceramide complex",
        img: "DrJart/11.jpg",
        name: "CERAMIDIN™ CREAM MIST",
        description: "",
        price: 19,
        size: "100ml",

    },
    {
        id: 12,
        category:"Toner",
        range: "Ceramide complex",
        img: "DrJart/12.jpg",
        name: "CERAMIDIN™ LIQUID",
        description: "",
        price: 17,
        size: "120ml",

    },
    {
        id: 13,
        category:"Mask",
        range: "Hyaluronic Acid",
        img: "DrJart/13.jpg",
        name: "DERMASK WATER JET VITAL HYDRA SOLUTION",
        description: "",
        price: 6,
        size: "27gr",

    },
    {
        id: 14,
        category:"Mask",
        range: "Ceramide complex",
        img: "DrJart/14.jpg",
        name: "CERAMIDIN FACIAL BARRIER MASK",
        description: "",
        price: 7,
        size: "22gr",

    },
    {
        id: 15,
        category:"Eye Care",
        range: "Ceramide complex",
        img: "DrJart/15.jpg",
        name: "CCERAMIDIN EYE CREAM",
        description: "",
        price: 135,
        size: "1",

    },
    {
        id: 16,
        category:"Mask",
        range: "Hyaluronic Acid",
        img: "DrJart/16.jpg",
        name: "CRYO RUBBER WITH MOISTURISING HYALURONIC ACID",
        description: "",
        price: 22,
        size: "100gr",

    },
    {
        id: 17,
        category:"Toner",
        range: "Niacinamide",
        img: "DrJart/17.jpg",
        name: "CTRL-A TEATREEMENT™ SOOTHING SPOT",
        description: "",
        price: 113,
        size: "100ml",

    },
    {
        id: 18,
        category:"Cleanser",
        range: "Niacinamide",
        img: "DrJart/18.jpg",
        name: "CTRL-A TEATREEMENT™ CLEANSING FOAM",
        description: "",
        price: 15,
        size: "100ml",

    },
    {
        id: 19,
        category:"Toner",
        range: "Niacinamide",
        img: "DrJart/19.jpg",
        name: "CTRL-A TEATREEMENT™ TONER",
        description: "",
        price: 40,
        size: "100ml",

    },
    {
        id: 20,
        category:"Serum",
        range: "Cantella Asiatica",
        img: "DrJart/20.jpg",
        name: "CICAPAIR™ TIGER GRASS RE.PAIR SERUM",
        description: "",
        price: 126,
        size: "100ml",

    },
    {
        id: 21,
        category:"Mist",
        range: "Cantella Asiatica",
        img: "DrJart/21.jpg",
        name: "CTRL-A TEATREEMENT™ SOOTHING SPOT",
        description: "",
        price: 30,
        size: "100ml",

    },
    {
        id: 22,
        category:"Cleanser",
        range: "Cantella Asiatica",
        img: "DrJart/22.jpg",
        name: "CICAPAIR™ TIGER GRASS ENZYME FOAM CLEANSER",
        description: "",
        price: 18,
        size: "100ml",

    },
    {
        id: 23,
        category:"Toner",
        range: "Hyaluronic Acid",
        img: "DrJart/23.jpg",
        name: "VITAL HYDRA SOLUTION BIOME ESSENCE WITH BLUE SHOT",
        description: "",
        price: 30,
        size: "100ml",

    },
    {
        id: 24,
        category:"Eye Care",
        range: "Hyaluronic Acid",
        img: "DrJart/24.jpg",
        name: "VITAL HYDRA SOLUTION™ BIOME EYE CREAM",
        description: "",
        price: 130,
        size: "100ml",

    },
    {
        id: 25,
        category:"Mask",
        range: "Cantella Asiatica",
        img: "DrJart/25.jpg",
        name: "CICAPAIR TIGER GRASS SLEEPAIR INTENSIVE MASK",
        description: "",
        price: 28,
        size: "100ml",

    },
    {
        id: 26,
        category:"Sets",
        range: "Cantella Asiatica",
        img: "DrJart/26.jpg",
        name: "CICAPAIR™ SKIN SOOTHING SET",
        description: "",
        price: 40,
        size: "100ml",

    },

]